# Generated by Django 4.2.4 on 2023-10-16 04:03

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acordao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data', models.DateField(verbose_name='Data')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('arquivo', models.FileField(upload_to='acordao', verbose_name='Arquivo')),
                ('data_inclusao', models.DateField(verbose_name='Data de Inclusão')),
                ('processo', models.CharField(max_length=255, verbose_name='Processo')),
                ('relator', models.CharField(max_length=255, verbose_name='Relator')),
            ],
            options={
                'verbose_name': 'Acordão',
                'verbose_name_plural': 'Acordãos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siga', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoLegislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Legislação',
                'verbose_name_plural': 'Tipos de Legislação',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data', models.DateField(verbose_name='Data')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('arquivo', models.FileField(upload_to='acordao', verbose_name='Arquivo')),
                ('data_inclusao', models.DateField(verbose_name='Data de Inclusão')),
                ('data_dou', models.DateField(verbose_name='Data de Publicação')),
                ('secao_dou', models.CharField(max_length=100, verbose_name='Seção da Publicação')),
                ('pagina_dou', models.CharField(max_length=100, verbose_name='Página da Publicação')),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcfmv.legislacao', verbose_name='Revogada Por')),
            ],
            options={
                'verbose_name': 'Legislação',
                'verbose_name_plural': 'Legislações',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=25, verbose_name='Sigla')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcfmv.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Conselho',
                'verbose_name_plural': 'Conselhos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
