# Generated by Django 4.2.4 on 2023-10-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='siga',
            new_name='sigla',
        ),
        migrations.AddField(
            model_name='legislacao',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lcfmv.tipolegislacao', verbose_name='Tipo'),
        ),
    ]
