# Generated by Django 4.2.4 on 2023-10-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0002_rename_siga_estado_sigla_legislacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='acordao', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='acordao',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Inclusão'),
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='acordao', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Inclusão'),
        ),
    ]
