# Generated by Django 4.2.4 on 2023-10-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0003_alter_acordao_arquivo_alter_acordao_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acordao',
            options={'verbose_name': 'Acórdão', 'verbose_name_plural': 'Acórdãos'},
        ),
        migrations.RemoveField(
            model_name='acordao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='acordao',
            name='data_inclusao',
        ),
        migrations.RemoveField(
            model_name='acordao',
            name='relator',
        ),
        migrations.RemoveField(
            model_name='legislacao',
            name='data_inclusao',
        ),
        migrations.AddField(
            model_name='acordao',
            name='data_dou',
            field=models.DateField(null=True, verbose_name='Data de Publicação no DOU'),
        ),
        migrations.AddField(
            model_name='acordao',
            name='natureza',
            field=models.CharField(choices=[['Processo Administrativo', 'Processo Administrativo'], ['Processo Ético-Profissional', 'Processo Ético-Profissional']], max_length=100, null=True, verbose_name='Natureza'),
        ),
        migrations.AddField(
            model_name='acordao',
            name='orgao_julgador',
            field=models.CharField(choices=[['Plenário', 'Plenário'], ['Primeira Turma', 'Primeira Turma'], ['Segunda Turma', 'Segunda Turma']], max_length=100, null=True, verbose_name='Órgão Julgador'),
        ),
        migrations.AddField(
            model_name='legislacao',
            name='codigo',
            field=models.IntegerField(null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='ano',
            field=models.IntegerField(null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='data_dou',
            field=models.DateField(null=True, verbose_name='Data de Publicação'),
        ),
    ]
