# Generated by Django 4.2.4 on 2023-10-28 07:17

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0004_alter_acordao_options_remove_acordao_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('numero_crmv', models.CharField(max_length=25, verbose_name='Nº CRMV')),
                ('classe', models.CharField(choices=[['V', 'Médico-Veterinário'], ['Z', 'Zootecnista']], max_length=100, verbose_name='Classe')),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcfmv.conselho', verbose_name='Conselho')),
            ],
            options={
                'verbose_name': 'Relator',
                'verbose_name_plural': 'Relatores',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
