# Generated by Django 4.2.4 on 2023-11-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0005_relator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordao',
            name='arquivo',
            field=models.FileField(null=True, upload_to='acordao', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='arquivo',
            field=models.FileField(null=True, upload_to='acordao', verbose_name='Arquivo'),
        ),
        migrations.AlterUniqueTogether(
            name='acordao',
            unique_together={('numero', 'ano', 'natureza', 'orgao_julgador')},
        ),
        migrations.AlterUniqueTogether(
            name='legislacao',
            unique_together={('numero', 'ano')},
        ),
    ]
