# Generated by Django 4.2.4 on 2023-11-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0007_alter_legislacao_data_dou'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordao',
            name='relator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lcfmv.relator', verbose_name='Relator'),
        ),
    ]
