# Generated by Django 4.2.4 on 2023-11-06 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0008_acordao_relator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordao',
            name='arquivo',
            field=models.FileField(default='', upload_to='acordao', verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acordao',
            name='data_dou',
            field=models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Publicação no DOU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acordao',
            name='natureza',
            field=models.CharField(choices=[['Processo Administrativo', 'Processo Administrativo'], ['Processo Ético-Profissional', 'Processo Ético-Profissional']], default='', max_length=100, verbose_name='Natureza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acordao',
            name='orgao_julgador',
            field=models.CharField(choices=[['Plenário', 'Plenário'], ['Primeira Turma', 'Primeira Turma'], ['Segunda Turma', 'Segunda Turma']], default='', max_length=100, verbose_name='Órgão Julgador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acordao',
            name='relator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lcfmv.relator', verbose_name='Relator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='ano',
            field=models.IntegerField(default=1900, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='arquivo',
            field=models.FileField(default='', upload_to='acordao', verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lcfmv.tipolegislacao', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
