# Generated by Django 4.2.4 on 2023-11-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcfmv', '0009_alter_acordao_arquivo_alter_acordao_data_dou_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legislacao',
            unique_together={('numero', 'ano', 'tipo')},
        ),
    ]
